# Generated by Django 5.1.5 on 2025-02-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fide_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=5, null=True)),
                ('federation', models.CharField(max_length=10)),
                ('club', models.CharField(blank=True, max_length=255, null=True)),
                ('fide_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('national_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fide_event_id', models.CharField(blank=True, max_length=20, null=True)),
                ('organizer', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('arbiter', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rounds', models.PositiveIntegerField()),
                ('time_control', models.CharField(max_length=50)),
                ('rating_average', models.PositiveIntegerField(blank=True, null=True)),
                ('rated_fide', models.BooleanField(default=False)),
                ('rated_national', models.BooleanField(default=False)),
                ('federation', models.CharField(max_length=10)),
                ('tie_breaks', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rounds', to='chess_tournaments.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('performance_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('tie_breaks', models.JSONField(default=dict)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='chess_tournaments.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_tournaments.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='chess_tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.PositiveIntegerField()),
                ('white_rating', models.PositiveIntegerField()),
                ('black_rating', models.PositiveIntegerField()),
                ('result', models.CharField(blank=True, choices=[('1-0', 'White Wins'), ('0-1', 'Black Wins'), ('½-½', 'Draw'), ('*', 'Unplayed')], max_length=5, null=True)),
                ('forfeit', models.BooleanField(default=False)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='chess_tournaments.player')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='chess_tournaments.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='chess_tournaments.round')),
            ],
            options={
                'unique_together': {('round', 'board')},
            },
        ),
    ]
