# Generated by Django 5.1.5 on 2025-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
