# Generated by Django 5.1.5 on 2025-02-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournaments', '0002_alter_game_black_rating_alter_game_white_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='chess_tournaments.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='chess_tournaments.player'),
        ),
    ]
