# Generated by Django 5.1.6 on 2025-02-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournaments', '0003_alter_game_black_player_alter_game_white_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='performance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tie_breaks',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='PlayerPerformance',
        ),
    ]
