# Generated by Django 5.1.6 on 2025-02-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournaments', '0004_player_performance_player_points_player_tie_breaks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='black_player',
            new_name='black',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='white_player',
            new_name='white',
        ),
    ]
