# Generated by Django 5.1.6 on 2025-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournaments', '0005_rename_black_player_game_black_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='organizer',
            new_name='organiser',
        ),
    ]
